//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:09:14 AM CEST 
//


package nl.connekt.bison.chb.passengerstopassignment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.connekt.bison.chb.passengerstopassignment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dataownercode_QNAME = new QName("", "dataownercode");
    private final static QName _Quaycode_QNAME = new QName("", "quaycode");
    private final static QName _Userstopcode_QNAME = new QName("", "userstopcode");
    private final static QName _Validfrom_QNAME = new QName("", "validfrom");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.connekt.bison.chb.passengerstopassignment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Userstopcodedata }
     * 
     */
    public Userstopcodedata createUserstopcodedata() {
        return new Userstopcodedata();
    }

    /**
     * Create an instance of {@link Userstopcodes }
     * 
     */
    public Userstopcodes createUserstopcodes() {
        return new Userstopcodes();
    }

    /**
     * Create an instance of {@link Quays }
     * 
     */
    public Quays createQuays() {
        return new Quays();
    }

    /**
     * Create an instance of {@link Quay }
     * 
     */
    public Quay createQuay() {
        return new Quay();
    }

    /**
     * Create an instance of {@link Export }
     * 
     */
    public Export createExport() {
        return new Export();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataownercode")
    public JAXBElement<String> createDataownercode(String value) {
        return new JAXBElement<String>(_Dataownercode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quaycode")
    public JAXBElement<String> createQuaycode(String value) {
        return new JAXBElement<String>(_Quaycode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userstopcode")
    public JAXBElement<String> createUserstopcode(String value) {
        return new JAXBElement<String>(_Userstopcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "validfrom")
    public JAXBElement<String> createValidfrom(String value) {
        return new JAXBElement<String>(_Validfrom_QNAME, String.class, null, value);
    }

}
