//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:09:14 AM CEST 
//


package nl.connekt.bison.chb.passengerstopassignment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}quaycode"/>
 *         &lt;element ref="{}userstopcodes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quaycode",
    "userstopcodes"
})
@XmlRootElement(name = "quay")
public class Quay {

    @XmlElement(required = true)
    protected String quaycode;
    @XmlElement(required = true)
    protected Userstopcodes userstopcodes;

    /**
     * Gets the value of the quaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuaycode() {
        return quaycode;
    }

    /**
     * Sets the value of the quaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuaycode(String value) {
        this.quaycode = value;
    }

    /**
     * Gets the value of the userstopcodes property.
     * 
     * @return
     *     possible object is
     *     {@link Userstopcodes }
     *     
     */
    public Userstopcodes getUserstopcodes() {
        return userstopcodes;
    }

    /**
     * Sets the value of the userstopcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userstopcodes }
     *     
     */
    public void setUserstopcodes(Userstopcodes value) {
        this.userstopcodes = value;
    }

}
