//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.17 at 01:56:36 AM CEST 
//


package nl.connekt.bison.kv6;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for KV6posinfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KV6posinfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *             &lt;element name="DELAY" type="{http://bison.connekt.nl/tmi8/kv6/msg}DELAYType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="INIT" type="{http://bison.connekt.nl/tmi8/kv6/msg}INITType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="ARRIVAL" type="{http://bison.connekt.nl/tmi8/kv6/msg}ARRIVALType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="ONSTOP" type="{http://bison.connekt.nl/tmi8/kv6/msg}ONSTOPType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="DEPARTURE" type="{http://bison.connekt.nl/tmi8/kv6/msg}DEPARTUREType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="ONROUTE" type="{http://bison.connekt.nl/tmi8/kv6/msg}ONROUTEType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="ONPATH" type="{http://bison.connekt.nl/tmi8/kv6/msg}ONPATHType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="OFFROUTE" type="{http://bison.connekt.nl/tmi8/kv6/msg}OFFROUTEType" maxOccurs="unbounded" minOccurs="0"/>
 *             &lt;element name="END" type="{http://bison.connekt.nl/tmi8/kv6/msg}ENDType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv6/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv6/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KV6posinfoType", propOrder = {
    "delayAndINITAndARRIVAL",
    "delimiterAndAny"
})
public class KV6PosinfoType {

    @XmlElements({
        @XmlElement(name = "DELAY", type = DELAYType.class),
        @XmlElement(name = "INIT", type = INITType.class),
        @XmlElement(name = "ARRIVAL", type = ARRIVALType.class),
        @XmlElement(name = "ONSTOP", type = ONSTOPType.class),
        @XmlElement(name = "DEPARTURE", type = DEPARTUREType.class),
        @XmlElement(name = "ONROUTE", type = ONROUTEType.class),
        @XmlElement(name = "ONPATH", type = ONPATHType.class),
        @XmlElement(name = "OFFROUTE", type = OFFROUTEType.class),
        @XmlElement(name = "END", type = ENDType.class)
    })
    protected List<Object> delayAndINITAndARRIVAL;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv6/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the delayAndINITAndARRIVAL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayAndINITAndARRIVAL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDELAYAndINITAndARRIVAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DELAYType }
     * {@link INITType }
     * {@link ARRIVALType }
     * {@link ONSTOPType }
     * {@link DEPARTUREType }
     * {@link ONROUTEType }
     * {@link ONPATHType }
     * {@link OFFROUTEType }
     * {@link ENDType }
     * 
     * 
     */
    public List<Object> getDELAYAndINITAndARRIVAL() {
        if (delayAndINITAndARRIVAL == null) {
            delayAndINITAndARRIVAL = new ArrayList<Object>();
        }
        return this.delayAndINITAndARRIVAL;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
