//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.17 at 01:56:36 AM CEST 
//


package nl.connekt.bison.kv6;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.connekt.bison.kv6 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.connekt.bison.kv6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VVTMREQ }
     * 
     */
    public VVTMREQ createVVTMREQ() {
        return new VVTMREQ();
    }

    /**
     * Create an instance of {@link VVTMPUSH }
     * 
     */
    public VVTMPUSH createVVTMPUSH() {
        return new VVTMPUSH();
    }

    /**
     * Create an instance of {@link KV6PosinfoType }
     * 
     */
    public KV6PosinfoType createKV6PosinfoType() {
        return new KV6PosinfoType();
    }

    /**
     * Create an instance of {@link VVTMRES }
     * 
     */
    public VVTMRES createVVTMRES() {
        return new VVTMRES();
    }

    /**
     * Create an instance of {@link DEPARTUREType }
     * 
     */
    public DEPARTUREType createDEPARTUREType() {
        return new DEPARTUREType();
    }

    /**
     * Create an instance of {@link OFFROUTEType }
     * 
     */
    public OFFROUTEType createOFFROUTEType() {
        return new OFFROUTEType();
    }

    /**
     * Create an instance of {@link DELAYType }
     * 
     */
    public DELAYType createDELAYType() {
        return new DELAYType();
    }

    /**
     * Create an instance of {@link ONPATHType }
     * 
     */
    public ONPATHType createONPATHType() {
        return new ONPATHType();
    }

    /**
     * Create an instance of {@link ONSTOPType }
     * 
     */
    public ONSTOPType createONSTOPType() {
        return new ONSTOPType();
    }

    /**
     * Create an instance of {@link ENDType }
     * 
     */
    public ENDType createENDType() {
        return new ENDType();
    }

    /**
     * Create an instance of {@link ONROUTEType }
     * 
     */
    public ONROUTEType createONROUTEType() {
        return new ONROUTEType();
    }

    /**
     * Create an instance of {@link INITType }
     * 
     */
    public INITType createINITType() {
        return new INITType();
    }

    /**
     * Create an instance of {@link ARRIVALType }
     * 
     */
    public ARRIVALType createARRIVALType() {
        return new ARRIVALType();
    }

    /**
     * Create an instance of {@link Delimiter }
     * 
     */
    public Delimiter createDelimiter() {
        return new Delimiter();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

}
