//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}daowcode"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}daowname"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}daowtype"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "daowcode",
    "daowname",
    "daowtype"
})
@XmlRootElement(name = "dataowner")
public class Dataowner {

    @XmlElement(required = true)
    protected String daowcode;
    @XmlElement(required = true)
    protected String daowname;
    @XmlElement(required = true)
    protected String daowtype;

    /**
     * Gets the value of the daowcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowcode() {
        return daowcode;
    }

    /**
     * Sets the value of the daowcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowcode(String value) {
        this.daowcode = value;
    }

    /**
     * Gets the value of the daowname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowname() {
        return daowname;
    }

    /**
     * Sets the value of the daowname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowname(String value) {
        this.daowname = value;
    }

    /**
     * Gets the value of the daowtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaowtype() {
        return daowtype;
    }

    /**
     * Sets the value of the daowtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaowtype(String value) {
        this.daowtype = value;
    }

}
