//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.connekt.bison.chb.export package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Quayshapetype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayshapetype");
    private final static QName _Stopplaceindication_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceindication");
    private final static QName _Daowcode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "daowcode");
    private final static QName _Greenstop_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "greenstop");
    private final static QName _Description_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "description");
    private final static QName _Stopplacecode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplacecode");
    private final static QName _Disabledaccessible_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "disabledaccessible");
    private final static QName _Guidelinestopplaceconnection_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "guidelinestopplaceconnection");
    private final static QName _Stopplaceimageurl_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceimageurl");
    private final static QName _Street_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "street");
    private final static QName _Guidelineconnection_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "guidelineconnection");
    private final static QName _Bayentranceangles_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "bayentranceangles");
    private final static QName _Ovccharging_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "ovccharging");
    private final static QName _Kerbheight_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "kerbheight");
    private final static QName _Stopplaceimagedescription_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceimagedescription");
    private final static QName _Quayname_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayname");
    private final static QName _Baylength_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "baylength");
    private final static QName _Leantosupport_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "leantosupport");
    private final static QName _Stopsidecode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopsidecode");
    private final static QName _Quaystatus_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quaystatus");
    private final static QName _Markedkerb_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "markedkerb");
    private final static QName _Publicname_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "publicname");
    private final static QName _Stopsign_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopsign");
    private final static QName _Location_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "location");
    private final static QName _Hectometersign_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "hectometersign");
    private final static QName _Remarks_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "remarks");
    private final static QName _Daowtype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "daowtype");
    private final static QName _Heightwithenvironment_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "heightwithenvironment");
    private final static QName _Internalname_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "internalname");
    private final static QName _Ptbikerental_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "ptbikerental");
    private final static QName _Audiobutton_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "audiobutton");
    private final static QName _Routenetworkmap_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "routenetworkmap");
    private final static QName _Stopplaceimagedate_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceimagedate");
    private final static QName _Quaytype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quaytype");
    private final static QName _Groundsurfaceindicator_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "groundsurfaceindicator");
    private final static QName _Tactilegroundsurfaceindicator_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "tactilegroundsurfaceindicator");
    private final static QName _Infounit_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "infounit");
    private final static QName _Stopinternalcode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopinternalcode");
    private final static QName _Stopobjectcode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopobjectcode");
    private final static QName _Bicycleparking_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "bicycleparking");
    private final static QName _Stopplaceownercode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceownercode");
    private final static QName _Level_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "level");
    private final static QName _Remarkstatus_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "remarkstatus");
    private final static QName _Town_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "town");
    private final static QName _Mutationdate_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "mutationdate");
    private final static QName _RdY_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "rd-y");
    private final static QName _RdZ_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "rd-z");
    private final static QName _RdX_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "rd-x");
    private final static QName _Transportmode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "transportmode");
    private final static QName _Stopsigntype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopsigntype");
    private final static QName _Placecode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "placecode");
    private final static QName _Quaycode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quaycode");
    private final static QName _Embaymentwidth_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "embaymentwidth");
    private final static QName _Uiccode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "uiccode");
    private final static QName _Quayimagedate_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayimagedate");
    private final static QName _Passengerinformationdisplaytype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "passengerinformationdisplaytype");
    private final static QName _Shelter_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "shelter");
    private final static QName _Roadcode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "roadcode");
    private final static QName _Seatavailable_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "seatavailable");
    private final static QName _Timetableinformation_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "timetableinformation");
    private final static QName _Visuallyaccessible_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "visuallyaccessible");
    private final static QName _Quayimageurl_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayimageurl");
    private final static QName _Boardingpositionwidth_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "boardingpositionwidth");
    private final static QName _Publicnamelong_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "publicnamelong");
    private final static QName _Liftedbicyclepath_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "liftedbicyclepath");
    private final static QName _Rampwidth_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "rampwidth");
    private final static QName _Compassdirection_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "compassdirection");
    private final static QName _Illuminatedstop_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "illuminatedstop");
    private final static QName _Municipalitycode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "municipalitycode");
    private final static QName _Parentquaycode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "parentquaycode");
    private final static QName _Bins_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "bins");
    private final static QName _Liftedpartlength_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "liftedpartlength");
    private final static QName _Numberofbicycleplaces_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "numberofbicycleplaces");
    private final static QName _Daowname_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "daowname");
    private final static QName _Publicnamemedium_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "publicnamemedium");
    private final static QName _Passengerinformationdisplay_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "passengerinformationdisplay");
    private final static QName _Environmentinfo_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "environmentinfo");
    private final static QName _Validfrom_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "validfrom");
    private final static QName _Stopplacetype_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplacetype");
    private final static QName _Concessionprovidercode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "concessionprovidercode");
    private final static QName _Alightingpositionwidth_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "alightingpositionwidth");
    private final static QName _Ovccico_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "ovccico");
    private final static QName _Stopinternalname_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopinternalname");
    private final static QName _Onlygetout_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "onlygetout");
    private final static QName _Shelterpublicity_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "shelterpublicity");
    private final static QName _Fulllengthguideline_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "fulllengthguideline");
    private final static QName _Environmentaccessroute_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "environmentaccessroute");
    private final static QName _Narrowestpassagewidth_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "narrowestpassagewidth");
    private final static QName _Guidelines_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "guidelines");
    private final static QName _Stopplaceaccessroute_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplaceaccessroute");
    private final static QName _Ramp_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "ramp");
    private final static QName _Bayexitangles_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "bayexitangles");
    private final static QName _Ramplength_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "ramplength");
    private final static QName _Toiletfacility_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "toiletfacility");
    private final static QName _Stopplacestatus_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "stopplacestatus");
    private final static QName _Quayimagedescription_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayimagedescription");
    private final static QName _Lift_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "lift");
    private final static QName _Quayownercode_QNAME = new QName("http://bison.connekt.nl/tmi8/chb/msg/v1.4", "quayownercode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.connekt.bison.chb.export
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Quaystatusdata }
     * 
     */
    public Quaystatusdata createQuaystatusdata() {
        return new Quaystatusdata();
    }

    /**
     * Create an instance of {@link Quaylocationdata }
     * 
     */
    public Quaylocationdata createQuaylocationdata() {
        return new Quaylocationdata();
    }

    /**
     * Create an instance of {@link Transportmodedata }
     * 
     */
    public Transportmodedata createTransportmodedata() {
        return new Transportmodedata();
    }

    /**
     * Create an instance of {@link Quaydisabledaccessible }
     * 
     */
    public Quaydisabledaccessible createQuaydisabledaccessible() {
        return new Quaydisabledaccessible();
    }

    /**
     * Create an instance of {@link Stopplacevisualaccessibility }
     * 
     */
    public Stopplacevisualaccessibility createStopplacevisualaccessibility() {
        return new Stopplacevisualaccessibility();
    }

    /**
     * Create an instance of {@link Quaybearing }
     * 
     */
    public Quaybearing createQuaybearing() {
        return new Quaybearing();
    }

    /**
     * Create an instance of {@link Quayphotos }
     * 
     */
    public Quayphotos createQuayphotos() {
        return new Quayphotos();
    }

    /**
     * Create an instance of {@link Quayphotodata }
     * 
     */
    public Quayphotodata createQuayphotodata() {
        return new Quayphotodata();
    }

    /**
     * Create an instance of {@link Dataowners }
     * 
     */
    public Dataowners createDataowners() {
        return new Dataowners();
    }

    /**
     * Create an instance of {@link Dataowner }
     * 
     */
    public Dataowner createDataowner() {
        return new Dataowner();
    }

    /**
     * Create an instance of {@link Quayvisuallyaccessible }
     * 
     */
    public Quayvisuallyaccessible createQuayvisuallyaccessible() {
        return new Quayvisuallyaccessible();
    }

    /**
     * Create an instance of {@link Quaymunicipality }
     * 
     */
    public Quaymunicipality createQuaymunicipality() {
        return new Quaymunicipality();
    }

    /**
     * Create an instance of {@link Stopplace }
     * 
     */
    public Stopplace createStopplace() {
        return new Stopplace();
    }

    /**
     * Create an instance of {@link Stopplacename }
     * 
     */
    public Stopplacename createStopplacename() {
        return new Stopplacename();
    }

    /**
     * Create an instance of {@link Stopplacestatusdata }
     * 
     */
    public Stopplacestatusdata createStopplacestatusdata() {
        return new Stopplacestatusdata();
    }

    /**
     * Create an instance of {@link Quays }
     * 
     */
    public Quays createQuays() {
        return new Quays();
    }

    /**
     * Create an instance of {@link Quay }
     * 
     */
    public Quay createQuay() {
        return new Quay();
    }

    /**
     * Create an instance of {@link Quaytypedata }
     * 
     */
    public Quaytypedata createQuaytypedata() {
        return new Quaytypedata();
    }

    /**
     * Create an instance of {@link Quaytransportmodes }
     * 
     */
    public Quaytransportmodes createQuaytransportmodes() {
        return new Quaytransportmodes();
    }

    /**
     * Create an instance of {@link Quayowner }
     * 
     */
    public Quayowner createQuayowner() {
        return new Quayowner();
    }

    /**
     * Create an instance of {@link Quayconcessionprovider }
     * 
     */
    public Quayconcessionprovider createQuayconcessionprovider() {
        return new Quayconcessionprovider();
    }

    /**
     * Create an instance of {@link Quaynamedata }
     * 
     */
    public Quaynamedata createQuaynamedata() {
        return new Quaynamedata();
    }

    /**
     * Create an instance of {@link Quayaccessibilityadaptions }
     * 
     */
    public Quayaccessibilityadaptions createQuayaccessibilityadaptions() {
        return new Quayaccessibilityadaptions();
    }

    /**
     * Create an instance of {@link Quayfacilities }
     * 
     */
    public Quayfacilities createQuayfacilities() {
        return new Quayfacilities();
    }

    /**
     * Create an instance of {@link Quayremarks }
     * 
     */
    public Quayremarks createQuayremarks() {
        return new Quayremarks();
    }

    /**
     * Create an instance of {@link Quayextraattributes }
     * 
     */
    public Quayextraattributes createQuayextraattributes() {
        return new Quayextraattributes();
    }

    /**
     * Create an instance of {@link Stopplacelocation }
     * 
     */
    public Stopplacelocation createStopplacelocation() {
        return new Stopplacelocation();
    }

    /**
     * Create an instance of {@link Stopplacemunicipality }
     * 
     */
    public Stopplacemunicipality createStopplacemunicipality() {
        return new Stopplacemunicipality();
    }

    /**
     * Create an instance of {@link Stopplaceowner }
     * 
     */
    public Stopplaceowner createStopplaceowner() {
        return new Stopplaceowner();
    }

    /**
     * Create an instance of {@link Stopplacedisabledaccessibility }
     * 
     */
    public Stopplacedisabledaccessibility createStopplacedisabledaccessibility() {
        return new Stopplacedisabledaccessibility();
    }

    /**
     * Create an instance of {@link Stopplaceaccessibilityadaptions }
     * 
     */
    public Stopplaceaccessibilityadaptions createStopplaceaccessibilityadaptions() {
        return new Stopplaceaccessibilityadaptions();
    }

    /**
     * Create an instance of {@link Stopplacefacilities }
     * 
     */
    public Stopplacefacilities createStopplacefacilities() {
        return new Stopplacefacilities();
    }

    /**
     * Create an instance of {@link Stopplaceremarks }
     * 
     */
    public Stopplaceremarks createStopplaceremarks() {
        return new Stopplaceremarks();
    }

    /**
     * Create an instance of {@link Stopplacephotos }
     * 
     */
    public Stopplacephotos createStopplacephotos() {
        return new Stopplacephotos();
    }

    /**
     * Create an instance of {@link Stopplacephotodata }
     * 
     */
    public Stopplacephotodata createStopplacephotodata() {
        return new Stopplacephotodata();
    }

    /**
     * Create an instance of {@link Stopplaces }
     * 
     */
    public Stopplaces createStopplaces() {
        return new Stopplaces();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Places }
     * 
     */
    public Places createPlaces() {
        return new Places();
    }

    /**
     * Create an instance of {@link Export }
     * 
     */
    public Export createExport() {
        return new Export();
    }

    /**
     * Create an instance of {@link Delimiter }
     * 
     */
    public Delimiter createDelimiter() {
        return new Delimiter();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayshapetype")
    public JAXBElement<String> createQuayshapetype(String value) {
        return new JAXBElement<String>(_Quayshapetype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceindication")
    public JAXBElement<String> createStopplaceindication(String value) {
        return new JAXBElement<String>(_Stopplaceindication_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "daowcode")
    public JAXBElement<String> createDaowcode(String value) {
        return new JAXBElement<String>(_Daowcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "greenstop")
    public JAXBElement<Boolean> createGreenstop(Boolean value) {
        return new JAXBElement<Boolean>(_Greenstop_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplacecode")
    public JAXBElement<String> createStopplacecode(String value) {
        return new JAXBElement<String>(_Stopplacecode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "disabledaccessible")
    public JAXBElement<String> createDisabledaccessible(String value) {
        return new JAXBElement<String>(_Disabledaccessible_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "guidelinestopplaceconnection")
    public JAXBElement<Boolean> createGuidelinestopplaceconnection(Boolean value) {
        return new JAXBElement<Boolean>(_Guidelinestopplaceconnection_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceimageurl")
    public JAXBElement<String> createStopplaceimageurl(String value) {
        return new JAXBElement<String>(_Stopplaceimageurl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "guidelineconnection")
    public JAXBElement<Boolean> createGuidelineconnection(Boolean value) {
        return new JAXBElement<Boolean>(_Guidelineconnection_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "bayentranceangles")
    public JAXBElement<BigDecimal> createBayentranceangles(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Bayentranceangles_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "ovccharging")
    public JAXBElement<Boolean> createOvccharging(Boolean value) {
        return new JAXBElement<Boolean>(_Ovccharging_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "kerbheight")
    public JAXBElement<BigDecimal> createKerbheight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Kerbheight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceimagedescription")
    public JAXBElement<String> createStopplaceimagedescription(String value) {
        return new JAXBElement<String>(_Stopplaceimagedescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayname")
    public JAXBElement<String> createQuayname(String value) {
        return new JAXBElement<String>(_Quayname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "baylength")
    public JAXBElement<BigDecimal> createBaylength(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Baylength_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "leantosupport")
    public JAXBElement<Boolean> createLeantosupport(Boolean value) {
        return new JAXBElement<Boolean>(_Leantosupport_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopsidecode")
    public JAXBElement<String> createStopsidecode(String value) {
        return new JAXBElement<String>(_Stopsidecode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quaystatus")
    public JAXBElement<String> createQuaystatus(String value) {
        return new JAXBElement<String>(_Quaystatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "markedkerb")
    public JAXBElement<Boolean> createMarkedkerb(Boolean value) {
        return new JAXBElement<Boolean>(_Markedkerb_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "publicname")
    public JAXBElement<String> createPublicname(String value) {
        return new JAXBElement<String>(_Publicname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopsign")
    public JAXBElement<Boolean> createStopsign(Boolean value) {
        return new JAXBElement<Boolean>(_Stopsign_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "location")
    public JAXBElement<String> createLocation(String value) {
        return new JAXBElement<String>(_Location_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "hectometersign")
    public JAXBElement<String> createHectometersign(String value) {
        return new JAXBElement<String>(_Hectometersign_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "remarks")
    public JAXBElement<String> createRemarks(String value) {
        return new JAXBElement<String>(_Remarks_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "daowtype")
    public JAXBElement<String> createDaowtype(String value) {
        return new JAXBElement<String>(_Daowtype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "heightwithenvironment")
    public JAXBElement<BigDecimal> createHeightwithenvironment(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Heightwithenvironment_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "internalname")
    public JAXBElement<String> createInternalname(String value) {
        return new JAXBElement<String>(_Internalname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "ptbikerental")
    public JAXBElement<Boolean> createPtbikerental(Boolean value) {
        return new JAXBElement<Boolean>(_Ptbikerental_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "audiobutton")
    public JAXBElement<Boolean> createAudiobutton(Boolean value) {
        return new JAXBElement<Boolean>(_Audiobutton_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "routenetworkmap")
    public JAXBElement<Boolean> createRoutenetworkmap(Boolean value) {
        return new JAXBElement<Boolean>(_Routenetworkmap_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceimagedate")
    public JAXBElement<XMLGregorianCalendar> createStopplaceimagedate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Stopplaceimagedate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quaytype")
    public JAXBElement<String> createQuaytype(String value) {
        return new JAXBElement<String>(_Quaytype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "groundsurfaceindicator")
    public JAXBElement<Boolean> createGroundsurfaceindicator(Boolean value) {
        return new JAXBElement<Boolean>(_Groundsurfaceindicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "tactilegroundsurfaceindicator")
    public JAXBElement<Boolean> createTactilegroundsurfaceindicator(Boolean value) {
        return new JAXBElement<Boolean>(_Tactilegroundsurfaceindicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "infounit")
    public JAXBElement<Boolean> createInfounit(Boolean value) {
        return new JAXBElement<Boolean>(_Infounit_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopinternalcode")
    public JAXBElement<String> createStopinternalcode(String value) {
        return new JAXBElement<String>(_Stopinternalcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopobjectcode")
    public JAXBElement<String> createStopobjectcode(String value) {
        return new JAXBElement<String>(_Stopobjectcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "bicycleparking")
    public JAXBElement<Boolean> createBicycleparking(Boolean value) {
        return new JAXBElement<Boolean>(_Bicycleparking_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceownercode")
    public JAXBElement<String> createStopplaceownercode(String value) {
        return new JAXBElement<String>(_Stopplaceownercode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "level")
    public JAXBElement<String> createLevel(String value) {
        return new JAXBElement<String>(_Level_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "remarkstatus")
    public JAXBElement<String> createRemarkstatus(String value) {
        return new JAXBElement<String>(_Remarkstatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "town")
    public JAXBElement<String> createTown(String value) {
        return new JAXBElement<String>(_Town_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "mutationdate")
    public JAXBElement<XMLGregorianCalendar> createMutationdate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Mutationdate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "rd-y")
    public JAXBElement<Integer> createRdY(Integer value) {
        return new JAXBElement<Integer>(_RdY_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "rd-z")
    public JAXBElement<Integer> createRdZ(Integer value) {
        return new JAXBElement<Integer>(_RdZ_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "rd-x")
    public JAXBElement<Integer> createRdX(Integer value) {
        return new JAXBElement<Integer>(_RdX_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "transportmode")
    public JAXBElement<String> createTransportmode(String value) {
        return new JAXBElement<String>(_Transportmode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopsigntype")
    public JAXBElement<String> createStopsigntype(String value) {
        return new JAXBElement<String>(_Stopsigntype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "placecode")
    public JAXBElement<String> createPlacecode(String value) {
        return new JAXBElement<String>(_Placecode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quaycode")
    public JAXBElement<String> createQuaycode(String value) {
        return new JAXBElement<String>(_Quaycode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "embaymentwidth")
    public JAXBElement<BigDecimal> createEmbaymentwidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Embaymentwidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "uiccode")
    public JAXBElement<Long> createUiccode(Long value) {
        return new JAXBElement<Long>(_Uiccode_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayimagedate")
    public JAXBElement<XMLGregorianCalendar> createQuayimagedate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Quayimagedate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "passengerinformationdisplaytype")
    public JAXBElement<String> createPassengerinformationdisplaytype(String value) {
        return new JAXBElement<String>(_Passengerinformationdisplaytype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "shelter")
    public JAXBElement<Boolean> createShelter(Boolean value) {
        return new JAXBElement<Boolean>(_Shelter_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "roadcode")
    public JAXBElement<String> createRoadcode(String value) {
        return new JAXBElement<String>(_Roadcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "seatavailable")
    public JAXBElement<Boolean> createSeatavailable(Boolean value) {
        return new JAXBElement<Boolean>(_Seatavailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "timetableinformation")
    public JAXBElement<Boolean> createTimetableinformation(Boolean value) {
        return new JAXBElement<Boolean>(_Timetableinformation_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "visuallyaccessible")
    public JAXBElement<String> createVisuallyaccessible(String value) {
        return new JAXBElement<String>(_Visuallyaccessible_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayimageurl")
    public JAXBElement<String> createQuayimageurl(String value) {
        return new JAXBElement<String>(_Quayimageurl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "boardingpositionwidth")
    public JAXBElement<BigDecimal> createBoardingpositionwidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Boardingpositionwidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "publicnamelong")
    public JAXBElement<String> createPublicnamelong(String value) {
        return new JAXBElement<String>(_Publicnamelong_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "liftedbicyclepath")
    public JAXBElement<Boolean> createLiftedbicyclepath(Boolean value) {
        return new JAXBElement<Boolean>(_Liftedbicyclepath_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "rampwidth")
    public JAXBElement<BigDecimal> createRampwidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Rampwidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "compassdirection")
    public JAXBElement<Integer> createCompassdirection(Integer value) {
        return new JAXBElement<Integer>(_Compassdirection_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "illuminatedstop")
    public JAXBElement<Boolean> createIlluminatedstop(Boolean value) {
        return new JAXBElement<Boolean>(_Illuminatedstop_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "municipalitycode")
    public JAXBElement<String> createMunicipalitycode(String value) {
        return new JAXBElement<String>(_Municipalitycode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "parentquaycode")
    public JAXBElement<String> createParentquaycode(String value) {
        return new JAXBElement<String>(_Parentquaycode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "bins")
    public JAXBElement<Boolean> createBins(Boolean value) {
        return new JAXBElement<Boolean>(_Bins_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "liftedpartlength")
    public JAXBElement<BigDecimal> createLiftedpartlength(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Liftedpartlength_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "numberofbicycleplaces")
    public JAXBElement<Integer> createNumberofbicycleplaces(Integer value) {
        return new JAXBElement<Integer>(_Numberofbicycleplaces_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "daowname")
    public JAXBElement<String> createDaowname(String value) {
        return new JAXBElement<String>(_Daowname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "publicnamemedium")
    public JAXBElement<String> createPublicnamemedium(String value) {
        return new JAXBElement<String>(_Publicnamemedium_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "passengerinformationdisplay")
    public JAXBElement<Boolean> createPassengerinformationdisplay(Boolean value) {
        return new JAXBElement<Boolean>(_Passengerinformationdisplay_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "environmentinfo")
    public JAXBElement<Boolean> createEnvironmentinfo(Boolean value) {
        return new JAXBElement<Boolean>(_Environmentinfo_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "validfrom")
    public JAXBElement<XMLGregorianCalendar> createValidfrom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Validfrom_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplacetype")
    public JAXBElement<String> createStopplacetype(String value) {
        return new JAXBElement<String>(_Stopplacetype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "concessionprovidercode")
    public JAXBElement<String> createConcessionprovidercode(String value) {
        return new JAXBElement<String>(_Concessionprovidercode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "alightingpositionwidth")
    public JAXBElement<BigDecimal> createAlightingpositionwidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Alightingpositionwidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "ovccico")
    public JAXBElement<Boolean> createOvccico(Boolean value) {
        return new JAXBElement<Boolean>(_Ovccico_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopinternalname")
    public JAXBElement<String> createStopinternalname(String value) {
        return new JAXBElement<String>(_Stopinternalname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "onlygetout")
    public JAXBElement<Boolean> createOnlygetout(Boolean value) {
        return new JAXBElement<Boolean>(_Onlygetout_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "shelterpublicity")
    public JAXBElement<Boolean> createShelterpublicity(Boolean value) {
        return new JAXBElement<Boolean>(_Shelterpublicity_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "fulllengthguideline")
    public JAXBElement<Boolean> createFulllengthguideline(Boolean value) {
        return new JAXBElement<Boolean>(_Fulllengthguideline_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "environmentaccessroute")
    public JAXBElement<Boolean> createEnvironmentaccessroute(Boolean value) {
        return new JAXBElement<Boolean>(_Environmentaccessroute_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "narrowestpassagewidth")
    public JAXBElement<BigDecimal> createNarrowestpassagewidth(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Narrowestpassagewidth_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "guidelines")
    public JAXBElement<Boolean> createGuidelines(Boolean value) {
        return new JAXBElement<Boolean>(_Guidelines_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplaceaccessroute")
    public JAXBElement<Boolean> createStopplaceaccessroute(Boolean value) {
        return new JAXBElement<Boolean>(_Stopplaceaccessroute_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "ramp")
    public JAXBElement<Boolean> createRamp(Boolean value) {
        return new JAXBElement<Boolean>(_Ramp_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "bayexitangles")
    public JAXBElement<BigDecimal> createBayexitangles(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Bayexitangles_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "ramplength")
    public JAXBElement<BigDecimal> createRamplength(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Ramplength_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "toiletfacility")
    public JAXBElement<Boolean> createToiletfacility(Boolean value) {
        return new JAXBElement<Boolean>(_Toiletfacility_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "stopplacestatus")
    public JAXBElement<String> createStopplacestatus(String value) {
        return new JAXBElement<String>(_Stopplacestatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayimagedescription")
    public JAXBElement<String> createQuayimagedescription(String value) {
        return new JAXBElement<String>(_Quayimagedescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "lift")
    public JAXBElement<Boolean> createLift(Boolean value) {
        return new JAXBElement<Boolean>(_Lift_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", name = "quayownercode")
    public JAXBElement<String> createQuayownercode(String value) {
        return new JAXBElement<String>(_Quayownercode_QNAME, String.class, null, value);
    }

}
