//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bison.connekt.nl/tmi8/chb/msg/v1.4", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.connekt.bison.chb.export;
