//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}validfrom"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayshapetype"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}baylength"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}markedkerb"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}lift"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}guidelines"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}groundsurfaceindicator"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopplaceaccessroute"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}mutationdate"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}embaymentwidth" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}bayentranceangles" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}bayexitangles" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}kerbheight" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}boardingpositionwidth" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}alightingpositionwidth" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}liftedpartlength" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}narrowestpassagewidth" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}fulllengthguideline" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}guidelinestopplaceconnection" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}tactilegroundsurfaceindicator" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}ramp" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}ramplength" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}heightwithenvironment" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}rampwidth" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "quayshapetype",
    "baylength",
    "markedkerb",
    "lift",
    "guidelines",
    "groundsurfaceindicator",
    "stopplaceaccessroute",
    "mutationdate",
    "embaymentwidth",
    "bayentranceangles",
    "bayexitangles",
    "kerbheight",
    "boardingpositionwidth",
    "alightingpositionwidth",
    "liftedpartlength",
    "narrowestpassagewidth",
    "fulllengthguideline",
    "guidelinestopplaceconnection",
    "tactilegroundsurfaceindicator",
    "ramp",
    "ramplength",
    "heightwithenvironment",
    "rampwidth"
})
@XmlRootElement(name = "quayaccessibilityadaptions")
public class Quayaccessibilityadaptions {

    @XmlElement(required = true)
    protected XMLGregorianCalendar validfrom;
    @XmlElement(required = true)
    protected String quayshapetype;
    @XmlElement(required = true)
    protected BigDecimal baylength;
    protected boolean markedkerb;
    protected boolean lift;
    protected boolean guidelines;
    protected boolean groundsurfaceindicator;
    protected boolean stopplaceaccessroute;
    @XmlElement(required = true)
    protected XMLGregorianCalendar mutationdate;
    protected BigDecimal embaymentwidth;
    protected BigDecimal bayentranceangles;
    protected BigDecimal bayexitangles;
    protected BigDecimal kerbheight;
    protected BigDecimal boardingpositionwidth;
    protected BigDecimal alightingpositionwidth;
    protected BigDecimal liftedpartlength;
    protected BigDecimal narrowestpassagewidth;
    protected Boolean fulllengthguideline;
    protected Boolean guidelinestopplaceconnection;
    protected Boolean tactilegroundsurfaceindicator;
    protected Boolean ramp;
    protected BigDecimal ramplength;
    protected BigDecimal heightwithenvironment;
    protected BigDecimal rampwidth;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidfrom(XMLGregorianCalendar value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the quayshapetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuayshapetype() {
        return quayshapetype;
    }

    /**
     * Sets the value of the quayshapetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuayshapetype(String value) {
        this.quayshapetype = value;
    }

    /**
     * Gets the value of the baylength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaylength() {
        return baylength;
    }

    /**
     * Sets the value of the baylength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaylength(BigDecimal value) {
        this.baylength = value;
    }

    /**
     * Gets the value of the markedkerb property.
     * 
     */
    public boolean isMarkedkerb() {
        return markedkerb;
    }

    /**
     * Sets the value of the markedkerb property.
     * 
     */
    public void setMarkedkerb(boolean value) {
        this.markedkerb = value;
    }

    /**
     * Gets the value of the lift property.
     * 
     */
    public boolean isLift() {
        return lift;
    }

    /**
     * Sets the value of the lift property.
     * 
     */
    public void setLift(boolean value) {
        this.lift = value;
    }

    /**
     * Gets the value of the guidelines property.
     * 
     */
    public boolean isGuidelines() {
        return guidelines;
    }

    /**
     * Sets the value of the guidelines property.
     * 
     */
    public void setGuidelines(boolean value) {
        this.guidelines = value;
    }

    /**
     * Gets the value of the groundsurfaceindicator property.
     * 
     */
    public boolean isGroundsurfaceindicator() {
        return groundsurfaceindicator;
    }

    /**
     * Sets the value of the groundsurfaceindicator property.
     * 
     */
    public void setGroundsurfaceindicator(boolean value) {
        this.groundsurfaceindicator = value;
    }

    /**
     * Gets the value of the stopplaceaccessroute property.
     * 
     */
    public boolean isStopplaceaccessroute() {
        return stopplaceaccessroute;
    }

    /**
     * Sets the value of the stopplaceaccessroute property.
     * 
     */
    public void setStopplaceaccessroute(boolean value) {
        this.stopplaceaccessroute = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutationdate(XMLGregorianCalendar value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the embaymentwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEmbaymentwidth() {
        return embaymentwidth;
    }

    /**
     * Sets the value of the embaymentwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEmbaymentwidth(BigDecimal value) {
        this.embaymentwidth = value;
    }

    /**
     * Gets the value of the bayentranceangles property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBayentranceangles() {
        return bayentranceangles;
    }

    /**
     * Sets the value of the bayentranceangles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBayentranceangles(BigDecimal value) {
        this.bayentranceangles = value;
    }

    /**
     * Gets the value of the bayexitangles property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBayexitangles() {
        return bayexitangles;
    }

    /**
     * Sets the value of the bayexitangles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBayexitangles(BigDecimal value) {
        this.bayexitangles = value;
    }

    /**
     * Gets the value of the kerbheight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKerbheight() {
        return kerbheight;
    }

    /**
     * Sets the value of the kerbheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKerbheight(BigDecimal value) {
        this.kerbheight = value;
    }

    /**
     * Gets the value of the boardingpositionwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBoardingpositionwidth() {
        return boardingpositionwidth;
    }

    /**
     * Sets the value of the boardingpositionwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBoardingpositionwidth(BigDecimal value) {
        this.boardingpositionwidth = value;
    }

    /**
     * Gets the value of the alightingpositionwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAlightingpositionwidth() {
        return alightingpositionwidth;
    }

    /**
     * Sets the value of the alightingpositionwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAlightingpositionwidth(BigDecimal value) {
        this.alightingpositionwidth = value;
    }

    /**
     * Gets the value of the liftedpartlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLiftedpartlength() {
        return liftedpartlength;
    }

    /**
     * Sets the value of the liftedpartlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLiftedpartlength(BigDecimal value) {
        this.liftedpartlength = value;
    }

    /**
     * Gets the value of the narrowestpassagewidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNarrowestpassagewidth() {
        return narrowestpassagewidth;
    }

    /**
     * Sets the value of the narrowestpassagewidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNarrowestpassagewidth(BigDecimal value) {
        this.narrowestpassagewidth = value;
    }

    /**
     * Gets the value of the fulllengthguideline property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFulllengthguideline() {
        return fulllengthguideline;
    }

    /**
     * Sets the value of the fulllengthguideline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFulllengthguideline(Boolean value) {
        this.fulllengthguideline = value;
    }

    /**
     * Gets the value of the guidelinestopplaceconnection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGuidelinestopplaceconnection() {
        return guidelinestopplaceconnection;
    }

    /**
     * Sets the value of the guidelinestopplaceconnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGuidelinestopplaceconnection(Boolean value) {
        this.guidelinestopplaceconnection = value;
    }

    /**
     * Gets the value of the tactilegroundsurfaceindicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTactilegroundsurfaceindicator() {
        return tactilegroundsurfaceindicator;
    }

    /**
     * Sets the value of the tactilegroundsurfaceindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTactilegroundsurfaceindicator(Boolean value) {
        this.tactilegroundsurfaceindicator = value;
    }

    /**
     * Gets the value of the ramp property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRamp() {
        return ramp;
    }

    /**
     * Sets the value of the ramp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRamp(Boolean value) {
        this.ramp = value;
    }

    /**
     * Gets the value of the ramplength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRamplength() {
        return ramplength;
    }

    /**
     * Sets the value of the ramplength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRamplength(BigDecimal value) {
        this.ramplength = value;
    }

    /**
     * Gets the value of the heightwithenvironment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHeightwithenvironment() {
        return heightwithenvironment;
    }

    /**
     * Sets the value of the heightwithenvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHeightwithenvironment(BigDecimal value) {
        this.heightwithenvironment = value;
    }

    /**
     * Gets the value of the rampwidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRampwidth() {
        return rampwidth;
    }

    /**
     * Sets the value of the rampwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRampwidth(BigDecimal value) {
        this.rampwidth = value;
    }

}
