//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaycode"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}validfrom"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaytypedata"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaytransportmodes"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaystatusdata"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaylocationdata"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaybearing"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayvisuallyaccessible"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaydisabledaccessible" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}mutationdate"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopobjectcode" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopinternalcode" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopinternalname" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}parentquaycode" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}onlygetout" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaymunicipality" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayowner" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayconcessionprovider" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quaynamedata" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayaccessibilityadaptions" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayfacilities" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayremarks" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayextraattributes" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}quayphotos" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quaycode",
    "validfrom",
    "quaytypedata",
    "quaytransportmodes",
    "quaystatusdata",
    "quaylocationdata",
    "quaybearing",
    "quayvisuallyaccessible",
    "quaydisabledaccessible",
    "mutationdate",
    "stopobjectcode",
    "stopinternalcode",
    "stopinternalname",
    "parentquaycode",
    "onlygetout",
    "quaymunicipality",
    "quayowner",
    "quayconcessionprovider",
    "quaynamedata",
    "quayaccessibilityadaptions",
    "quayfacilities",
    "quayremarks",
    "quayextraattributes",
    "quayphotos"
})
@XmlRootElement(name = "quay")
public class Quay {

    @XmlElement(required = true)
    protected String quaycode;
    @XmlElement(required = true)
    protected XMLGregorianCalendar validfrom;
    @XmlElement(required = true)
    protected Quaytypedata quaytypedata;
    @XmlElement(required = true)
    protected Quaytransportmodes quaytransportmodes;
    @XmlElement(required = true)
    protected Quaystatusdata quaystatusdata;
    @XmlElement(required = true)
    protected Quaylocationdata quaylocationdata;
    @XmlElement(required = true)
    protected Quaybearing quaybearing;
    @XmlElement(required = true)
    protected Quayvisuallyaccessible quayvisuallyaccessible;
    @XmlElement(required = true)
    protected List<Quaydisabledaccessible> quaydisabledaccessible;
    @XmlElement(required = true)
    protected XMLGregorianCalendar mutationdate;
    protected String stopobjectcode;
    protected String stopinternalcode;
    protected String stopinternalname;
    protected String parentquaycode;
    protected Boolean onlygetout;
    protected Quaymunicipality quaymunicipality;
    protected Quayowner quayowner;
    protected Quayconcessionprovider quayconcessionprovider;
    protected Quaynamedata quaynamedata;
    protected Quayaccessibilityadaptions quayaccessibilityadaptions;
    protected Quayfacilities quayfacilities;
    protected Quayremarks quayremarks;
    protected Quayextraattributes quayextraattributes;
    protected Quayphotos quayphotos;

    /**
     * Gets the value of the quaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuaycode() {
        return quaycode;
    }

    /**
     * Sets the value of the quaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuaycode(String value) {
        this.quaycode = value;
    }

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidfrom(XMLGregorianCalendar value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the quaytypedata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaytypedata }
     *     
     */
    public Quaytypedata getQuaytypedata() {
        return quaytypedata;
    }

    /**
     * Sets the value of the quaytypedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaytypedata }
     *     
     */
    public void setQuaytypedata(Quaytypedata value) {
        this.quaytypedata = value;
    }

    /**
     * Gets the value of the quaytransportmodes property.
     * 
     * @return
     *     possible object is
     *     {@link Quaytransportmodes }
     *     
     */
    public Quaytransportmodes getQuaytransportmodes() {
        return quaytransportmodes;
    }

    /**
     * Sets the value of the quaytransportmodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaytransportmodes }
     *     
     */
    public void setQuaytransportmodes(Quaytransportmodes value) {
        this.quaytransportmodes = value;
    }

    /**
     * Gets the value of the quaystatusdata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaystatusdata }
     *     
     */
    public Quaystatusdata getQuaystatusdata() {
        return quaystatusdata;
    }

    /**
     * Sets the value of the quaystatusdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaystatusdata }
     *     
     */
    public void setQuaystatusdata(Quaystatusdata value) {
        this.quaystatusdata = value;
    }

    /**
     * Gets the value of the quaylocationdata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaylocationdata }
     *     
     */
    public Quaylocationdata getQuaylocationdata() {
        return quaylocationdata;
    }

    /**
     * Sets the value of the quaylocationdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaylocationdata }
     *     
     */
    public void setQuaylocationdata(Quaylocationdata value) {
        this.quaylocationdata = value;
    }

    /**
     * Gets the value of the quaybearing property.
     * 
     * @return
     *     possible object is
     *     {@link Quaybearing }
     *     
     */
    public Quaybearing getQuaybearing() {
        return quaybearing;
    }

    /**
     * Sets the value of the quaybearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaybearing }
     *     
     */
    public void setQuaybearing(Quaybearing value) {
        this.quaybearing = value;
    }

    /**
     * Gets the value of the quayvisuallyaccessible property.
     * 
     * @return
     *     possible object is
     *     {@link Quayvisuallyaccessible }
     *     
     */
    public Quayvisuallyaccessible getQuayvisuallyaccessible() {
        return quayvisuallyaccessible;
    }

    /**
     * Sets the value of the quayvisuallyaccessible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayvisuallyaccessible }
     *     
     */
    public void setQuayvisuallyaccessible(Quayvisuallyaccessible value) {
        this.quayvisuallyaccessible = value;
    }

    /**
     * Gets the value of the quaydisabledaccessible property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quaydisabledaccessible property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuaydisabledaccessible().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Quaydisabledaccessible }
     * 
     * 
     */
    public List<Quaydisabledaccessible> getQuaydisabledaccessible() {
        if (quaydisabledaccessible == null) {
            quaydisabledaccessible = new ArrayList<Quaydisabledaccessible>();
        }
        return this.quaydisabledaccessible;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutationdate(XMLGregorianCalendar value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the stopobjectcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopobjectcode() {
        return stopobjectcode;
    }

    /**
     * Sets the value of the stopobjectcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopobjectcode(String value) {
        this.stopobjectcode = value;
    }

    /**
     * Gets the value of the stopinternalcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopinternalcode() {
        return stopinternalcode;
    }

    /**
     * Sets the value of the stopinternalcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopinternalcode(String value) {
        this.stopinternalcode = value;
    }

    /**
     * Gets the value of the stopinternalname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopinternalname() {
        return stopinternalname;
    }

    /**
     * Sets the value of the stopinternalname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopinternalname(String value) {
        this.stopinternalname = value;
    }

    /**
     * Gets the value of the parentquaycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentquaycode() {
        return parentquaycode;
    }

    /**
     * Sets the value of the parentquaycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentquaycode(String value) {
        this.parentquaycode = value;
    }

    /**
     * Gets the value of the onlygetout property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnlygetout() {
        return onlygetout;
    }

    /**
     * Sets the value of the onlygetout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnlygetout(Boolean value) {
        this.onlygetout = value;
    }

    /**
     * Gets the value of the quaymunicipality property.
     * 
     * @return
     *     possible object is
     *     {@link Quaymunicipality }
     *     
     */
    public Quaymunicipality getQuaymunicipality() {
        return quaymunicipality;
    }

    /**
     * Sets the value of the quaymunicipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaymunicipality }
     *     
     */
    public void setQuaymunicipality(Quaymunicipality value) {
        this.quaymunicipality = value;
    }

    /**
     * Gets the value of the quayowner property.
     * 
     * @return
     *     possible object is
     *     {@link Quayowner }
     *     
     */
    public Quayowner getQuayowner() {
        return quayowner;
    }

    /**
     * Sets the value of the quayowner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayowner }
     *     
     */
    public void setQuayowner(Quayowner value) {
        this.quayowner = value;
    }

    /**
     * Gets the value of the quayconcessionprovider property.
     * 
     * @return
     *     possible object is
     *     {@link Quayconcessionprovider }
     *     
     */
    public Quayconcessionprovider getQuayconcessionprovider() {
        return quayconcessionprovider;
    }

    /**
     * Sets the value of the quayconcessionprovider property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayconcessionprovider }
     *     
     */
    public void setQuayconcessionprovider(Quayconcessionprovider value) {
        this.quayconcessionprovider = value;
    }

    /**
     * Gets the value of the quaynamedata property.
     * 
     * @return
     *     possible object is
     *     {@link Quaynamedata }
     *     
     */
    public Quaynamedata getQuaynamedata() {
        return quaynamedata;
    }

    /**
     * Sets the value of the quaynamedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quaynamedata }
     *     
     */
    public void setQuaynamedata(Quaynamedata value) {
        this.quaynamedata = value;
    }

    /**
     * Gets the value of the quayaccessibilityadaptions property.
     * 
     * @return
     *     possible object is
     *     {@link Quayaccessibilityadaptions }
     *     
     */
    public Quayaccessibilityadaptions getQuayaccessibilityadaptions() {
        return quayaccessibilityadaptions;
    }

    /**
     * Sets the value of the quayaccessibilityadaptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayaccessibilityadaptions }
     *     
     */
    public void setQuayaccessibilityadaptions(Quayaccessibilityadaptions value) {
        this.quayaccessibilityadaptions = value;
    }

    /**
     * Gets the value of the quayfacilities property.
     * 
     * @return
     *     possible object is
     *     {@link Quayfacilities }
     *     
     */
    public Quayfacilities getQuayfacilities() {
        return quayfacilities;
    }

    /**
     * Sets the value of the quayfacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayfacilities }
     *     
     */
    public void setQuayfacilities(Quayfacilities value) {
        this.quayfacilities = value;
    }

    /**
     * Gets the value of the quayremarks property.
     * 
     * @return
     *     possible object is
     *     {@link Quayremarks }
     *     
     */
    public Quayremarks getQuayremarks() {
        return quayremarks;
    }

    /**
     * Sets the value of the quayremarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayremarks }
     *     
     */
    public void setQuayremarks(Quayremarks value) {
        this.quayremarks = value;
    }

    /**
     * Gets the value of the quayextraattributes property.
     * 
     * @return
     *     possible object is
     *     {@link Quayextraattributes }
     *     
     */
    public Quayextraattributes getQuayextraattributes() {
        return quayextraattributes;
    }

    /**
     * Sets the value of the quayextraattributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayextraattributes }
     *     
     */
    public void setQuayextraattributes(Quayextraattributes value) {
        this.quayextraattributes = value;
    }

    /**
     * Gets the value of the quayphotos property.
     * 
     * @return
     *     possible object is
     *     {@link Quayphotos }
     *     
     */
    public Quayphotos getQuayphotos() {
        return quayphotos;
    }

    /**
     * Sets the value of the quayphotos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quayphotos }
     *     
     */
    public void setQuayphotos(Quayphotos value) {
        this.quayphotos = value;
    }

}
