//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopplaceimagedate"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopplaceimageurl"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}stopplaceimagedescription"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}mutationdate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stopplaceimagedate",
    "stopplaceimageurl",
    "stopplaceimagedescription",
    "mutationdate"
})
@XmlRootElement(name = "stopplacephotodata")
public class Stopplacephotodata {

    @XmlElement(required = true)
    protected XMLGregorianCalendar stopplaceimagedate;
    @XmlElement(required = true)
    protected String stopplaceimageurl;
    @XmlElement(required = true)
    protected String stopplaceimagedescription;
    @XmlElement(required = true)
    protected XMLGregorianCalendar mutationdate;

    /**
     * Gets the value of the stopplaceimagedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStopplaceimagedate() {
        return stopplaceimagedate;
    }

    /**
     * Sets the value of the stopplaceimagedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStopplaceimagedate(XMLGregorianCalendar value) {
        this.stopplaceimagedate = value;
    }

    /**
     * Gets the value of the stopplaceimageurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopplaceimageurl() {
        return stopplaceimageurl;
    }

    /**
     * Sets the value of the stopplaceimageurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopplaceimageurl(String value) {
        this.stopplaceimageurl = value;
    }

    /**
     * Gets the value of the stopplaceimagedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopplaceimagedescription() {
        return stopplaceimagedescription;
    }

    /**
     * Sets the value of the stopplaceimagedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopplaceimagedescription(String value) {
        this.stopplaceimagedescription = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutationdate(XMLGregorianCalendar value) {
        this.mutationdate = value;
    }

}
