//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.27 at 12:15:06 AM CEST 
//


package nl.connekt.bison.chb.export;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}validfrom"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}mutationdate"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}timetableinformation" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}passengerinformationdisplay" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}passengerinformationdisplaytype" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}environmentinfo" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}bicycleparking" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}numberofbicycleplaces" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}toiletfacility" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}ptbikerental" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}bins" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}ovccico" minOccurs="0"/>
 *         &lt;element ref="{http://bison.connekt.nl/tmi8/chb/msg/v1.4}ovccharging" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "validfrom",
    "mutationdate",
    "timetableinformation",
    "passengerinformationdisplay",
    "passengerinformationdisplaytype",
    "environmentinfo",
    "bicycleparking",
    "numberofbicycleplaces",
    "toiletfacility",
    "ptbikerental",
    "bins",
    "ovccico",
    "ovccharging"
})
@XmlRootElement(name = "stopplacefacilities")
public class Stopplacefacilities {

    @XmlElement(required = true)
    protected XMLGregorianCalendar validfrom;
    @XmlElement(required = true)
    protected XMLGregorianCalendar mutationdate;
    protected Boolean timetableinformation;
    protected Boolean passengerinformationdisplay;
    protected String passengerinformationdisplaytype;
    protected Boolean environmentinfo;
    protected Boolean bicycleparking;
    protected Integer numberofbicycleplaces;
    protected Boolean toiletfacility;
    protected Boolean ptbikerental;
    protected Boolean bins;
    protected Boolean ovccico;
    protected Boolean ovccharging;

    /**
     * Gets the value of the validfrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidfrom() {
        return validfrom;
    }

    /**
     * Sets the value of the validfrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidfrom(XMLGregorianCalendar value) {
        this.validfrom = value;
    }

    /**
     * Gets the value of the mutationdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMutationdate() {
        return mutationdate;
    }

    /**
     * Sets the value of the mutationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMutationdate(XMLGregorianCalendar value) {
        this.mutationdate = value;
    }

    /**
     * Gets the value of the timetableinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTimetableinformation() {
        return timetableinformation;
    }

    /**
     * Sets the value of the timetableinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTimetableinformation(Boolean value) {
        this.timetableinformation = value;
    }

    /**
     * Gets the value of the passengerinformationdisplay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassengerinformationdisplay() {
        return passengerinformationdisplay;
    }

    /**
     * Sets the value of the passengerinformationdisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassengerinformationdisplay(Boolean value) {
        this.passengerinformationdisplay = value;
    }

    /**
     * Gets the value of the passengerinformationdisplaytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerinformationdisplaytype() {
        return passengerinformationdisplaytype;
    }

    /**
     * Sets the value of the passengerinformationdisplaytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerinformationdisplaytype(String value) {
        this.passengerinformationdisplaytype = value;
    }

    /**
     * Gets the value of the environmentinfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnvironmentinfo() {
        return environmentinfo;
    }

    /**
     * Sets the value of the environmentinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnvironmentinfo(Boolean value) {
        this.environmentinfo = value;
    }

    /**
     * Gets the value of the bicycleparking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBicycleparking() {
        return bicycleparking;
    }

    /**
     * Sets the value of the bicycleparking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBicycleparking(Boolean value) {
        this.bicycleparking = value;
    }

    /**
     * Gets the value of the numberofbicycleplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberofbicycleplaces() {
        return numberofbicycleplaces;
    }

    /**
     * Sets the value of the numberofbicycleplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberofbicycleplaces(Integer value) {
        this.numberofbicycleplaces = value;
    }

    /**
     * Gets the value of the toiletfacility property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToiletfacility() {
        return toiletfacility;
    }

    /**
     * Sets the value of the toiletfacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToiletfacility(Boolean value) {
        this.toiletfacility = value;
    }

    /**
     * Gets the value of the ptbikerental property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPtbikerental() {
        return ptbikerental;
    }

    /**
     * Sets the value of the ptbikerental property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPtbikerental(Boolean value) {
        this.ptbikerental = value;
    }

    /**
     * Gets the value of the bins property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBins() {
        return bins;
    }

    /**
     * Sets the value of the bins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBins(Boolean value) {
        this.bins = value;
    }

    /**
     * Gets the value of the ovccico property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccico() {
        return ovccico;
    }

    /**
     * Sets the value of the ovccico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccico(Boolean value) {
        this.ovccico = value;
    }

    /**
     * Gets the value of the ovccharging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvccharging() {
        return ovccharging;
    }

    /**
     * Sets the value of the ovccharging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvccharging(Boolean value) {
        this.ovccharging = value;
    }

}
