//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for CHANGEDESTINATIONType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CHANGEDESTINATIONType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userstopcode" type="{http://bison.connekt.nl/tmi8/kv17/msg}codeType"/>
 *         &lt;element name="passagesequencenumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}passagesequencenumberType"/>
 *         &lt;element name="destinationcode" type="{http://bison.connekt.nl/tmi8/kv17/msg}codeType" minOccurs="0"/>
 *         &lt;element name="destinationname50" type="{http://bison.connekt.nl/tmi8/kv17/msg}destinationname50Type"/>
 *         &lt;element name="destinationname16" type="{http://bison.connekt.nl/tmi8/kv17/msg}destinationname16Type"/>
 *         &lt;element name="destinationdetail16" type="{http://bison.connekt.nl/tmi8/kv17/msg}destinationdetail16Type" minOccurs="0"/>
 *         &lt;element name="destinationdisplay16" type="{http://bison.connekt.nl/tmi8/kv17/msg}destinationdisplay16Type" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv17/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv17/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CHANGEDESTINATIONType", propOrder = {
    "userstopcode",
    "passagesequencenumber",
    "destinationcode",
    "destinationname50",
    "destinationname16",
    "destinationdetail16",
    "destinationdisplay16",
    "delimiterAndAny"
})
public class CHANGEDESTINATIONType {

    @XmlElement(required = true)
    protected String userstopcode;
    protected int passagesequencenumber;
    protected String destinationcode;
    @XmlElement(required = true)
    protected String destinationname50;
    @XmlElement(required = true)
    protected String destinationname16;
    protected String destinationdetail16;
    protected String destinationdisplay16;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv17/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the userstopcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstopcode() {
        return userstopcode;
    }

    /**
     * Sets the value of the userstopcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstopcode(String value) {
        this.userstopcode = value;
    }

    /**
     * Gets the value of the passagesequencenumber property.
     * 
     */
    public int getPassagesequencenumber() {
        return passagesequencenumber;
    }

    /**
     * Sets the value of the passagesequencenumber property.
     * 
     */
    public void setPassagesequencenumber(int value) {
        this.passagesequencenumber = value;
    }

    /**
     * Gets the value of the destinationcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationcode() {
        return destinationcode;
    }

    /**
     * Sets the value of the destinationcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationcode(String value) {
        this.destinationcode = value;
    }

    /**
     * Gets the value of the destinationname50 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationname50() {
        return destinationname50;
    }

    /**
     * Sets the value of the destinationname50 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationname50(String value) {
        this.destinationname50 = value;
    }

    /**
     * Gets the value of the destinationname16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationname16() {
        return destinationname16;
    }

    /**
     * Sets the value of the destinationname16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationname16(String value) {
        this.destinationname16 = value;
    }

    /**
     * Gets the value of the destinationdetail16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationdetail16() {
        return destinationdetail16;
    }

    /**
     * Sets the value of the destinationdetail16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationdetail16(String value) {
        this.destinationdetail16 = value;
    }

    /**
     * Gets the value of the destinationdisplay16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationdisplay16() {
        return destinationdisplay16;
    }

    /**
     * Sets the value of the destinationdisplay16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationdisplay16(String value) {
        this.destinationdisplay16 = value;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
