//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for CHANGEPASSTIMESType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CHANGEPASSTIMESType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userstopcode" type="{http://bison.connekt.nl/tmi8/kv17/msg}codeType"/>
 *         &lt;element name="passagesequencenumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}passagesequencenumberType"/>
 *         &lt;element name="targetarrivaltime" type="{http://bison.connekt.nl/tmi8/kv17/msg}tmitimeType"/>
 *         &lt;element name="targetdeparturetime" type="{http://bison.connekt.nl/tmi8/kv17/msg}tmitimeType"/>
 *         &lt;element name="journeystoptype" type="{http://bison.connekt.nl/tmi8/kv17/msg}journeystoptypeType"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv17/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv17/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CHANGEPASSTIMESType", propOrder = {
    "userstopcode",
    "passagesequencenumber",
    "targetarrivaltime",
    "targetdeparturetime",
    "journeystoptype",
    "delimiterAndAny"
})
public class CHANGEPASSTIMESType {

    @XmlElement(required = true)
    protected String userstopcode;
    protected int passagesequencenumber;
    @XmlElement(required = true)
    protected String targetarrivaltime;
    @XmlElement(required = true)
    protected String targetdeparturetime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected JourneystoptypeType journeystoptype;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv17/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the userstopcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstopcode() {
        return userstopcode;
    }

    /**
     * Sets the value of the userstopcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstopcode(String value) {
        this.userstopcode = value;
    }

    /**
     * Gets the value of the passagesequencenumber property.
     * 
     */
    public int getPassagesequencenumber() {
        return passagesequencenumber;
    }

    /**
     * Sets the value of the passagesequencenumber property.
     * 
     */
    public void setPassagesequencenumber(int value) {
        this.passagesequencenumber = value;
    }

    /**
     * Gets the value of the targetarrivaltime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetarrivaltime() {
        return targetarrivaltime;
    }

    /**
     * Sets the value of the targetarrivaltime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetarrivaltime(String value) {
        this.targetarrivaltime = value;
    }

    /**
     * Gets the value of the targetdeparturetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetdeparturetime() {
        return targetdeparturetime;
    }

    /**
     * Sets the value of the targetdeparturetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetdeparturetime(String value) {
        this.targetdeparturetime = value;
    }

    /**
     * Gets the value of the journeystoptype property.
     * 
     * @return
     *     possible object is
     *     {@link JourneystoptypeType }
     *     
     */
    public JourneystoptypeType getJourneystoptype() {
        return journeystoptype;
    }

    /**
     * Sets the value of the journeystoptype property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneystoptypeType }
     *     
     */
    public void setJourneystoptype(JourneystoptypeType value) {
        this.journeystoptype = value;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
