//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for KV17cvlinfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KV17cvlinfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KV17JOURNEY" type="{http://bison.connekt.nl/tmi8/kv17/msg}KV17journeyType"/>
 *         &lt;element name="KV17MUTATEJOURNEY" type="{http://bison.connekt.nl/tmi8/kv17/msg}KV17mutatejourneyType" minOccurs="0"/>
 *         &lt;element name="KV17MUTATEJOURNEYSTOP" type="{http://bison.connekt.nl/tmi8/kv17/msg}KV17mutatejourneystopType" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv17/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv17/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KV17cvlinfoType", propOrder = {
    "kv17JOURNEY",
    "kv17MUTATEJOURNEY",
    "kv17MUTATEJOURNEYSTOP",
    "delimiterAndAny"
})
public class KV17CvlinfoType {

    @XmlElement(name = "KV17JOURNEY", required = true)
    protected KV17JourneyType kv17JOURNEY;
    @XmlElement(name = "KV17MUTATEJOURNEY")
    protected KV17MutatejourneyType kv17MUTATEJOURNEY;
    @XmlElement(name = "KV17MUTATEJOURNEYSTOP")
    protected KV17MutatejourneystopType kv17MUTATEJOURNEYSTOP;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv17/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the kv17JOURNEY property.
     * 
     * @return
     *     possible object is
     *     {@link KV17JourneyType }
     *     
     */
    public KV17JourneyType getKV17JOURNEY() {
        return kv17JOURNEY;
    }

    /**
     * Sets the value of the kv17JOURNEY property.
     * 
     * @param value
     *     allowed object is
     *     {@link KV17JourneyType }
     *     
     */
    public void setKV17JOURNEY(KV17JourneyType value) {
        this.kv17JOURNEY = value;
    }

    /**
     * Gets the value of the kv17MUTATEJOURNEY property.
     * 
     * @return
     *     possible object is
     *     {@link KV17MutatejourneyType }
     *     
     */
    public KV17MutatejourneyType getKV17MUTATEJOURNEY() {
        return kv17MUTATEJOURNEY;
    }

    /**
     * Sets the value of the kv17MUTATEJOURNEY property.
     * 
     * @param value
     *     allowed object is
     *     {@link KV17MutatejourneyType }
     *     
     */
    public void setKV17MUTATEJOURNEY(KV17MutatejourneyType value) {
        this.kv17MUTATEJOURNEY = value;
    }

    /**
     * Gets the value of the kv17MUTATEJOURNEYSTOP property.
     * 
     * @return
     *     possible object is
     *     {@link KV17MutatejourneystopType }
     *     
     */
    public KV17MutatejourneystopType getKV17MUTATEJOURNEYSTOP() {
        return kv17MUTATEJOURNEYSTOP;
    }

    /**
     * Sets the value of the kv17MUTATEJOURNEYSTOP property.
     * 
     * @param value
     *     allowed object is
     *     {@link KV17MutatejourneystopType }
     *     
     */
    public void setKV17MUTATEJOURNEYSTOP(KV17MutatejourneystopType value) {
        this.kv17MUTATEJOURNEYSTOP = value;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
