//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for KV17journeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KV17journeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataownercode" type="{http://bison.connekt.nl/tmi8/kv17/msg}dataownercodeType"/>
 *         &lt;element name="lineplanningnumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}lineplanningnumberType"/>
 *         &lt;element name="operatingday" type="{http://bison.connekt.nl/tmi8/kv17/msg}tmidateType"/>
 *         &lt;element name="journeynumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}journeynumberType"/>
 *         &lt;element name="reinforcementnumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}reinforcementnumberType"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv17/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv17/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KV17journeyType", propOrder = {
    "dataownercode",
    "lineplanningnumber",
    "operatingday",
    "journeynumber",
    "reinforcementnumber",
    "delimiterAndAny"
})
public class KV17JourneyType {

    @XmlElement(required = true)
    protected String dataownercode;
    @XmlElement(required = true)
    protected String lineplanningnumber;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar operatingday;
    protected int journeynumber;
    protected int reinforcementnumber;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv17/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the dataownercode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataownercode() {
        return dataownercode;
    }

    /**
     * Sets the value of the dataownercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataownercode(String value) {
        this.dataownercode = value;
    }

    /**
     * Gets the value of the lineplanningnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineplanningnumber() {
        return lineplanningnumber;
    }

    /**
     * Sets the value of the lineplanningnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineplanningnumber(String value) {
        this.lineplanningnumber = value;
    }

    /**
     * Gets the value of the operatingday property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOperatingday() {
        return operatingday;
    }

    /**
     * Sets the value of the operatingday property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOperatingday(XMLGregorianCalendar value) {
        this.operatingday = value;
    }

    /**
     * Gets the value of the journeynumber property.
     * 
     */
    public int getJourneynumber() {
        return journeynumber;
    }

    /**
     * Sets the value of the journeynumber property.
     * 
     */
    public void setJourneynumber(int value) {
        this.journeynumber = value;
    }

    /**
     * Gets the value of the reinforcementnumber property.
     * 
     */
    public int getReinforcementnumber() {
        return reinforcementnumber;
    }

    /**
     * Sets the value of the reinforcementnumber property.
     * 
     */
    public void setReinforcementnumber(int value) {
        this.reinforcementnumber = value;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
