//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for MUTATIONMESSAGEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MUTATIONMESSAGEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userstopcode" type="{http://bison.connekt.nl/tmi8/kv17/msg}codeType"/>
 *         &lt;element name="passagesequencenumber" type="{http://bison.connekt.nl/tmi8/kv17/msg}passagesequencenumberType"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="reasontype" type="{http://bison.connekt.nl/tmi8/kv17/msg}sirisxcategoryType"/>
 *           &lt;element name="subreasontype" type="{http://bison.connekt.nl/tmi8/kv17/msg}sirisxcodeType"/>
 *         &lt;/sequence>
 *         &lt;element name="reasoncontent" type="{http://bison.connekt.nl/tmi8/kv17/msg}contentType" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="advicetype" type="{http://bison.connekt.nl/tmi8/kv17/msg}sirisxcategoryType"/>
 *           &lt;element name="subadvicetype" type="{http://bison.connekt.nl/tmi8/kv17/msg}sirisxcodeType"/>
 *         &lt;/sequence>
 *         &lt;element name="advicecontent" type="{http://bison.connekt.nl/tmi8/kv17/msg}contentType" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://bison.connekt.nl/tmi8/kv17/core}delimiter"/>
 *           &lt;any processContents='lax' namespace=' http://bison.connekt.nl/tmi8/kv17/msg' maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MUTATIONMESSAGEType", propOrder = {
    "userstopcode",
    "passagesequencenumber",
    "reasontype",
    "subreasontype",
    "reasoncontent",
    "advicetype",
    "subadvicetype",
    "advicecontent",
    "delimiterAndAny"
})
public class MUTATIONMESSAGEType {

    @XmlElement(required = true)
    protected String userstopcode;
    protected int passagesequencenumber;
    protected Integer reasontype;
    protected String subreasontype;
    protected String reasoncontent;
    protected Integer advicetype;
    protected String subadvicetype;
    protected String advicecontent;
    @XmlElementRef(name = "delimiter", namespace = "http://bison.connekt.nl/tmi8/kv17/core", type = Delimiter.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> delimiterAndAny;

    /**
     * Gets the value of the userstopcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstopcode() {
        return userstopcode;
    }

    /**
     * Sets the value of the userstopcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstopcode(String value) {
        this.userstopcode = value;
    }

    /**
     * Gets the value of the passagesequencenumber property.
     * 
     */
    public int getPassagesequencenumber() {
        return passagesequencenumber;
    }

    /**
     * Sets the value of the passagesequencenumber property.
     * 
     */
    public void setPassagesequencenumber(int value) {
        this.passagesequencenumber = value;
    }

    /**
     * Gets the value of the reasontype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReasontype() {
        return reasontype;
    }

    /**
     * Sets the value of the reasontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReasontype(Integer value) {
        this.reasontype = value;
    }

    /**
     * Gets the value of the subreasontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubreasontype() {
        return subreasontype;
    }

    /**
     * Sets the value of the subreasontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubreasontype(String value) {
        this.subreasontype = value;
    }

    /**
     * Gets the value of the reasoncontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasoncontent() {
        return reasoncontent;
    }

    /**
     * Sets the value of the reasoncontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasoncontent(String value) {
        this.reasoncontent = value;
    }

    /**
     * Gets the value of the advicetype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAdvicetype() {
        return advicetype;
    }

    /**
     * Sets the value of the advicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAdvicetype(Integer value) {
        this.advicetype = value;
    }

    /**
     * Gets the value of the subadvicetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubadvicetype() {
        return subadvicetype;
    }

    /**
     * Sets the value of the subadvicetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubadvicetype(String value) {
        this.subadvicetype = value;
    }

    /**
     * Gets the value of the advicecontent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvicecontent() {
        return advicecontent;
    }

    /**
     * Sets the value of the advicecontent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvicecontent(String value) {
        this.advicecontent = value;
    }

    /**
     * Gets the value of the delimiterAndAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delimiterAndAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelimiterAndAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Delimiter }
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDelimiterAndAny() {
        if (delimiterAndAny == null) {
            delimiterAndAny = new ArrayList<Object>();
        }
        return this.delimiterAndAny;
    }

}
