//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 10:39:38 PM CEST 
//


package nl.connekt.bison.kv17;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.connekt.bison.kv17 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.connekt.bison.kv17
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VVTMREQ }
     * 
     */
    public VVTMREQ createVVTMREQ() {
        return new VVTMREQ();
    }

    /**
     * Create an instance of {@link VVTMPUSH }
     * 
     */
    public VVTMPUSH createVVTMPUSH() {
        return new VVTMPUSH();
    }

    /**
     * Create an instance of {@link KV17CvlinfoType }
     * 
     */
    public KV17CvlinfoType createKV17CvlinfoType() {
        return new KV17CvlinfoType();
    }

    /**
     * Create an instance of {@link VVTMRES }
     * 
     */
    public VVTMRES createVVTMRES() {
        return new VVTMRES();
    }

    /**
     * Create an instance of {@link SHORTENType }
     * 
     */
    public SHORTENType createSHORTENType() {
        return new SHORTENType();
    }

    /**
     * Create an instance of {@link LAGType }
     * 
     */
    public LAGType createLAGType() {
        return new LAGType();
    }

    /**
     * Create an instance of {@link KV17MutatejourneyType }
     * 
     */
    public KV17MutatejourneyType createKV17MutatejourneyType() {
        return new KV17MutatejourneyType();
    }

    /**
     * Create an instance of {@link KV17JourneyType }
     * 
     */
    public KV17JourneyType createKV17JourneyType() {
        return new KV17JourneyType();
    }

    /**
     * Create an instance of {@link CANCELType }
     * 
     */
    public CANCELType createCANCELType() {
        return new CANCELType();
    }

    /**
     * Create an instance of {@link CHANGEDESTINATIONType }
     * 
     */
    public CHANGEDESTINATIONType createCHANGEDESTINATIONType() {
        return new CHANGEDESTINATIONType();
    }

    /**
     * Create an instance of {@link MUTATIONMESSAGEType }
     * 
     */
    public MUTATIONMESSAGEType createMUTATIONMESSAGEType() {
        return new MUTATIONMESSAGEType();
    }

    /**
     * Create an instance of {@link CHANGEPASSTIMESType }
     * 
     */
    public CHANGEPASSTIMESType createCHANGEPASSTIMESType() {
        return new CHANGEPASSTIMESType();
    }

    /**
     * Create an instance of {@link KV17MutatejourneystopType }
     * 
     */
    public KV17MutatejourneystopType createKV17MutatejourneystopType() {
        return new KV17MutatejourneystopType();
    }

    /**
     * Create an instance of {@link RECOVERType }
     * 
     */
    public RECOVERType createRECOVERType() {
        return new RECOVERType();
    }

    /**
     * Create an instance of {@link ADDType }
     * 
     */
    public ADDType createADDType() {
        return new ADDType();
    }

    /**
     * Create an instance of {@link Delimiter }
     * 
     */
    public Delimiter createDelimiter() {
        return new Delimiter();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

}
